### ISSUE TITLE
zsh completion not working for me

### ISSUE THREAD

**Issue by gedw99** [Tom5521/fsize#6]
Cant seem to get the completion to work. 

Can you advise me ?

https://github.com/Tom5521/fsize/blob/main/update/update_completions.go#L10 shows where they should be put on disk ?

I am on Mac m2.

```sh
ls -al /usr/share/zsh/site-functions
total 0
drwxr-xr-x  2 root  wheel   64 May  7 17:01 .
drwxr-xr-x  4 root  wheel  128 May  7 17:01 ..
```

The following make file works but not the completions.

```make
# https://github.com/Tom5521/fsize

NAME=fsize

DEP_ROOT=$(PWD)/.dep
export PATH:=$(PATH):$(DEP_ROOT)

print:

dep-init:
	mkdir -p $(DEP_ROOT)
dep: dep-init
	go install github.com/Tom5521/fsize@latest
	mv $(GOPATH)/bin/fsize $(DEP_ROOT)/$(NAME)
dep-del:
	rm -rf $(DEP_ROOT)

run:
	$(NAME) $(ARGS)
run-h:
	$(NAME) -h
run-completion:
	$(MAKE) run ARGS=--gen-bash-completion
	$(MAKE) run ARGS=--gen-fish-completion
	$(MAKE) run ARGS=--gen-zsh-completion
	mv *.fish $(DEP_ROOT)
	mv *.sh $(DEP_ROOT)
	mv *.zsh $(DEP_ROOT)
run-completion-list:
	@echo ""
	ls -al /usr/share/zsh/site-functions
run-update:
	$(MAKE) run ARGS=--update
	$(MAKE) run-completion-list
	




```

**Comment by Tom5521** [comment]
> https://github.com/Tom5521/fsize/blob/main/update/update_completions.go#L10 shows where they should be put on disk ?

Yes, now that I see those locations are wrong because they should be `/usr/local/share` and not `/usr/share` according to [this](https://unix.stackexchange.com/a/607827/625459).

Either way it works but it is bad practice.

Back to the topic, you can install the completions at the system level by running these commands as administrator

```bash
mkdir -p /usr/local/share/zsh/site-functions
fsize --gen-zsh-completion /usr/local/share/zsh/site-functions/_fsize
```


Anyway, you can also see where to install the completions in `$fpath`

**Comment by Tom5521** [comment]
Don't worry about it, I already fixed it in the latest version ;)
